fix: migrated & fixed
chatwoot/chatwoot-flutter-sdk pull request #59
Opened 2024-10-23 10:33 UTC by hungryemon

2024-10-24 23:58 UTC, Bitch2022 requested changes

2024-10-24 23:58 UTC, Bitch2022 commented on example/android/build.gradle
> +tasks.register("clean", Delete) {
Run

2024-10-26 21:12 UTC, Bitch2022 approved these changes

2024-10-27 06:42 UTC, hungryemon reviewed
ok

2024-11-17 03:59 UTC, closed without merging